---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-assembler-conf
  namespace: {{ .Release.Namespace | quote }}
data:
  pv-assembler.yaml: |
    ---
    version: 1
    volumes:
    {{- range .Values.volumes }}
      - {{ . }}
    {{- end }}
