---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-assembler-conf
  namespace: {{ .Release.Namespace | quote }}
data:
  pv-assembler.yaml: |
    ---
    version: 1
    {{- range .Values.volumes }}
    volumes:
      {{ default .claimName .localName }}:
        allowed_namespaces:
          {{- toYaml .allowedNamespaces | nindent 10 }}
    {{- end }}
