---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-assembler
  namespace: default
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assemble-pvs
rules:
  - apiGroups: ["ilya-epifanov.github.com"]
    resources: ["pv-parts"]
    verbs:
    - get
    - watch
    - list
    - patch
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pv-assembler-binding
subjects:
- kind: ServiceAccount
  namespace: default
  name: pv-assembler
roleRef:
  kind: ClusterRole
  name: assemble-pvs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pv-assembler
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  serviceName: pv-assembler
  selector:
    matchLabels:
      app: pv-assembler
  template:
    metadata:
      labels:
        app: pv-assembler
    spec:
      serviceAccountName: pv-assembler
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conf
          configMap:
            name: pv-assembler-conf
            defaultMode: 420
      {{- range .Values.volumes }}
        - name: volume-{{ default .claimName .localName }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
      {{- end }}
      containers:
        - name: pv-assembler
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: conf
              mountPath: /conf
          {{- with .Values.dataVolumeClaimTemplateSpec }}
            - name: data
              mountPath: /data
          {{- end }}
          {{- range .Values.volumes }}
            - name: volume-{{ default .claimName .localName }}
              mountPath: /volumes/{{ default .claimName .localName }}
          {{- end }}
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          env:
            - name: RUST_LOG
              value: hyper=warn,tower=warn,sled=warn,kube=info,{{ .Values.logLevel }}
          ports:
            - containerPort: 80
  {{- with .Values.dataVolumeClaimTemplateSpec }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- toYaml . | nindent 8 }}
  {{- end }}
